services:
  - type: web
    name: storefly-api
    env: node
    rootDir: storefly-api
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
